name: Publish

on:
  release:
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check version
        run: |
          CARGO_VERSION=$(grep -oP 'version = "\K(.*?)(?=")' Cargo.toml)
          GITHUB_VERSION=${{ github.ref }}
          GITHUB_VERSION=${GITHUB_VERSION#refs/tags/}
          if [ "$CARGO_VERSION" != "$GITHUB_VERSION" ]; then
            echo "Cargo.toml version ($CARGO_VERSION) does not match GitHub release tag ($GITHUB_VERSION)"
            exit 1
          fi

      - name: Publish to crates.io
        uses: actions-rs/cargo@v1
        with:
          command: publish
          args: --token ${{ secrets.CRATES_IO_TOKEN }}
